"""
Comparison Page Template

Formats a structured comparison page using
agent-generated comparison data.
"""

from typing import Dict, Any


def build_comparison_page(
    primary_product: Any,
    comparison_product: Dict[str, Any]
) -> Dict:
    """
    Assemble a comparison page.

    Args:
        primary_product: Parsed primary product
        comparison_product: Fictional product generated by agent

    Returns:
        Comparison page dictionary
    """
    return {
        "page_type": "comparison",
        "products": [
            {
                "name": primary_product.name,
                "ingredients": primary_product.ingredients,
                "benefits": primary_product.benefits,
                "price_inr": primary_product.price
            },
            {
                "name": comparison_product["name"],
                "ingredients": comparison_product["ingredients"],
                "benefits": comparison_product["benefits"],
                "price_inr": comparison_product["price"]
            }
        ]
    }
